### ISSUE TITLE
Material Preview Hatası

### ISSUE THREAD

**Issue by FatihGedik** [Ad-Hoc-Game/MyProjectV1.0#3]
Material terrain üzerinde Preview yazısı kötü görünüyor.Oluşturulan terrain kötü bir görüntü oluşturuyor. @RamazanBakir  ##
![prew](https://user-images.githubusercontent.com/45772336/81484493-74a07a80-924e-11ea-91ad-49a712166f13.png)

**Comment by RamazanBakir** [comment]
Sorunun Çözümü Sırası ile : 
Show -> Visualize ' a giriş yapıyoruz.
Sonrasında Preview Shadows İndicator tiklemesini kapatmak yeterli olacaktır. 
Alternatif çözüm olarak "Lighting build"  yapılabilir.

**Comment by FatihGedik** [comment]
Bu çözüm sadece oyun tasarımı aşamasında çözülmesine yardımcı oluyor. Ayrıca bazı ligthning faultların giderilmesini sağlıyor. Ancak oyun ''play'' modundayken bu sorun tekrar çıkıyor ve terrain üzerinde ''Preview'' halen yazıyor.
teşekkürler.

**Comment by RamazanBakir** [comment]
O halde şu yol kesin çözüm olabilir;
Sırasıyla,
View Options -> Show Engine Content , sonrasında Show Engine Content klasörüne giriş yapmak gerekiyor.
Giriş yaptıktan sonra "Preview Shadow Indıcator Metal" isimli materiali açıyoruz.İçerideki materialin blueprintinden  "Emissive Color"'un bağlantısını kaldırıp.Save edip çalıştırırsak düzelecektir.
Olması gereken blueprint şu şekil de ;
![Ekran Alıntısı](https://user-images.githubusercontent.com/48602486/81484747-d1049980-9250-11ea-8091-d0fa1d8c32ff.PNG)
