### ISSUE TITLE
Binaların İçinden Geçiş Hatası

### ISSUE THREAD

**Issue by FatihGedik** [Ad-Hoc-Game/MyProjectV1.0#4]
Karakterin binaların kapısı hariç içlerinden geçmesi düzeltildi. @RamazanBakir

**Comment by RamazanBakir** [comment]
Binaların dışı tamamen **merge** edilebilir.Bu sayede asset sayısı azalmış olur ve compile hızlandırılabilir.
Ayrıca binaların içinden geçmemek için Static Meshlere Collision yapılabilir.
Proje içindeki bazı binalara Collision sekmesinden 26DOP Simplified Collison ayarlanmıştır.
